name: CI for API Gateway

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'


    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simploCine-api-gateway:latest .


    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/simploCine-api-gateway:latest


    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/simploCine-api-gateway:latest
            docker stop simploCine-api-gateway || true
            docker rm simploCine-api-gateway || true
            sudo docker run -d --name simploCine-api-gateway -p 80:80 ${{ secrets.DOCKER_USERNAME }}/simploCine-sessions:latest