name: CI for API Gateway

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up .NET Core SDK (Utilisez une version stable comme 7.x ou 6.x)
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'  # Ou '6.x' pour la version LTS

    # Build the project
    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    # Run unit tests
    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal

    # Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simploCine-api-gateway:latest .

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/simploCine-api-gateway:latest

    # Deploy to VPS
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/simploCine-api-gateway:latest
            docker stop simploCine-api-gateway || true
            docker rm simploCine-api-gateway || true
            docker run -d --name simploCine-api-gateway -p 80:80 ${{ secrets.DOCKER_USERNAME }}/simploCine-api-gateway:latest